name: Test build
'on':
  push:
    branches:
    - master
  schedule:
  - cron: '0 9 * * *'
jobs:
  job:
    name: Test build
    runs-on: ubuntu-22.04
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3
    - name: Checkout Freelancer
      uses: darklab8/infra/.github/actions/checkout-freelancer@master
      with:
        freelancer-mod: discovery
        freelancer-folder: ${{ github.workspace }}/fl-data
        ssh-key-base64-discovery: ${{ secrets.ID_RSA_FILES_FREELANCER_DISCOVERY }}
    - run: ls ./fl-data
    - name: Install Go
      uses: darklab8/infra/.github/actions/install-go@master
    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master
    - name: Install Templ
      uses: darklab8/infra/.github/actions/install-templ@master
    - name: generate Templ files
      run: templ generate
    - name: add versions
      run: task build-version
    - name: Patch freelancer discovery to latest
      uses: darklab8/infra/.github/actions/patch-disco@master
      with:
        freelancer-folder: ${{ github.workspace }}/fl-data
    - name: Test things
      run: task test -- -v
      env:
        FLDARKDATA_LOG_LEVEL: DEBUG
    - name: build
      run: task build
      env:
        SITE_ROOT: /fl-darkstat/
        FREELANCER_FOLDER: ${{ github.workspace }}/fl-data
        FLDARKSTAT_HEADING: <span style="font-weight:1000;">DEV ENV</span> <a href="https://github.com/darklab8/fl-darkstat">fl-darkstat</a> for <a href="https://github.com/darklab8/fl-data-discovery">Freelancer Discovery</a>
        DARKSTAT_DETAILED: 'false'
        RELAY_HOST: https://darkrelay-staging.dd84ai.com
